spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: dummy
            client-secret: dummy
          twitter:
            client-id: dummy
            client-secret: dummy
